{% set name = "skyfield" %}
{% set version = "1.11" %}
{% set sha256 = "54ecaa0160841479859665a75149e93871b193236f3d4335f1172ddafec82452" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: python -m pip install --no-deps --ignore-installed . 

requirements:
  build:
    - python
    - pip
    - jplephem
  run:
    - python
    - numpy
    - astropy 
    - pytz 
    - lxml 
    - html5lib 
    - beautifulsoup4

test:
  requires:
    - mock
    - nose
    - jplephem
    - sgp4
  imports:
    - skyfield
    - skyfield.data
    - skyfield.tests
  commands:
    - nosetests -v skyfield.tests.test_functions
    - nosetests -v skyfield.tests.test_angles

about:
  home: http://rhodesmill.org/skyfield/
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'Elegant astronomy for Python'

  description: |
    Skyfield computes positions for the stars, planets, and satellites in orbit around the Earth. 
    Its results should agree with the positions generated by the United States Naval Observatory 
    and their Astronomical Almanac to within 0.0005 arcseconds (which equals half a milliarcsecond). 
    Written in pure Python and installs without any compilation.
    Supports Python 2.6-2.7 and Python 3.3-3.6. Has NumPy as its only binary dependency, 
    the fundamental package for scientific computing with Python, whose vector operations make 
    Skyfield efficient.  
  doc_url: http://rhodesmill.org/skyfield/toc.html
  dev_url: https://github.com/skyfielders/python-skyfield

extra:
  recipe-maintainers:
    - jochym
    - brandon-rhodes
