{% set name = "skyfield" %}
{% set version = "1.0" %}
{% set sha256 = "69f3ee8463a80b92f4e5b0f7c5e01c14325226740084ac1be225652938e54ca4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 2
  script: python setup.py install

requirements:
  build:
    - python
    - jplephem
  run:
    - python
    - numpy
    - astropy 
    - pytz 
    - lxml 
    - html5lib 
    - beautifulsoup4

test:
  requires:
    - mock
    - nose
    - jplephem
    - sgp4
  imports:
    - skyfield
    - skyfield.data
    - skyfield.tests
  commands:
    - nosetests -v skyfield.tests.test_functions
    - nosetests -v skyfield.tests.test_angles

about:
  home: http://rhodesmill.org/skyfield/
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'Elegant astronomy for Python'

  description: |
    Skyfield is a pure-Python astronomy package that is compatible with both 
    Python 2 and 3 and makes it easy to generate high precision research-grade 
    positions for planets and Earth satellites.  
  doc_url: http://rhodesmill.org/skyfield/toc.html
  dev_url: https://github.com/skyfielders/python-skyfield

extra:
  recipe-maintainers:
    - jochym
    - brandon-rhodes
