travis:
  secure:
    BINSTAR_TOKEN: rcq5t62s7RnzTzrAc29wQAsFaPfZLa8p/QRfHbPKAlvMnl9iosoV2JCPdeKr0k1zNW4U9mFc8+Md78OeoT58p3CYBJi8V6+cfE1DoQo2DmzbLhjXE+H6d5/0pPS1/qibeY32NxLNBCeG6pYICsui1VeKzp9XAbpvbIYioP2VhYdgTNOz9OomkKUcsib4uu9YA6kEVL/sZY2Qrvq8oIyYUpA/Rc80rukgs8g5F/hQcoO7M6werEuqbrEJMiNFIV6+JvmUrUNErH+n3zFIqWO3bq9Gqz4LyfpPgxv1oeJ55AjtTeztXcpMc4ki1C2qUYxjwwR/e3TLy/obpj4Xp1FHFQFgMp65ezR7TLlkLkKI+JVC31oEzoJ28rkvWGPAIcfDDzUQihurCc7FdHwUdHWnUQPmzrIS5HxcT9ljBzdBuOcdQWkafGyKr3p2PPirclqDFp0ipo/igVl3r5QcVKkU9keugRt7IFp9NxF5WxirAb7LFq3Rx3rfTWG+UQLfreGqIpYXTBUxkrMzgKPBUpd+C40UqMZ21drUpFDlLYh9T8jX0JL3+CvVffc61ZNRauMpbfzKciX6AdoLfrBprF5LGcVIH7LbDZiKGP5W/od8hXRs9ENQT3NSluGagh3cUwdWdnPy08DWdksA4DVHbb8/4no9FZU8Zyfx3c7TpYh4pAU=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
