travis:
  secure:
    BINSTAR_TOKEN: fgcDnHtUw5qNxFRPEhBmPub9bAfW64H+lRHpzxYRDSSrMq1Ir9IC6dG+F5aG2v7xUqTsdPY1skwz+KKp2Ii/g2+cHf5lJrs9fBvq0zEkCx3Vg60zL0aac5VAd7N67r8x8ufhtotsGlsRNQVffmrsqQ5KacHPqCtQkhE1dnvJM5TZ/8oJ2ebv4HSu6DOgbshrcMjZrCNgzdGYYCdT7LGlY4XkScoRWzkb9ma1ccFtb+fG7hLKtc1ZJHRbrq0RnugUGqwaNM0Ayn+Wi0cSkC0esgmPWv2K5n/4sKi6ExA3G0FMIc9K7uykTwHCXfYxG7ldFA8nqqd/q+jsp/LgA1nsCrJQa68JKm6oLDeeRVaGJD+j9xsky+M2oyeDeyFToGiBe7rMmwWObhvuRcDAMtkyKCeIFQEVDM4jlMlmue7sNV4M7r2hzOD5WPHExo7+p5Sz2d8h2uVTPZ3RXpZxoQ8vt6D+FJbaD3Y17iow/+p31VsTAU+5gaCUth8t3xDo2SjR9opVrpFJ3C8eNfHlL9+T4hZud006cQnbvFTWk7AUXqKekE2Hfuz8upY2mFESDkX110pyshwUZkLejEgDrQmq0QKtjXznzCtmr+rp8toY55uwfcD7IQ5ZzqRxPvk4X+q7kiq3Y2ZFXsmG+8jmO08i32wtNXoBh2MhOEnIMoAI3gA=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
